services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-container
    volumes:
      - $PWD:/workspace
      - ~/.ssh:/home/devuser/.ssh
      - /var/run/docker.sock:/var/run/docker.sock  # Allows running Docker commands on the host
    security_opt:
      - label=disable 
    working_dir: /workspace
    stdin_open: true
    tty: true
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
      - "8080:8080"
      - "5009:5009"
      - "8989:8989"
